### ISSUE TITLE
Devices not synced after HA restart

### ISSUE THREAD

**Issue by walberjunior** [rmoesbergen/openwrt-ha-device-tracker#37] opened 2023-09-24 13:44 UTC
As I said in the other issue, after restarting HA the devices are not synchronized, making it necessary to force a reconnection with the router, moving around the house to change routers or turning the WiFi off and on.

![image](https://github.com/rmoesbergen/openwrt-ha-device-tracker/assets/20650850/e4853431-f792-4cd5-9c2c-8546115d8aa2)

**Comment by dckiller51** [comment] 2023-09-26 13:09
Same problem. I'm looking at how to restart the service remotely with this component [hass_openwrt](https://github.com/kvj/hass_openwrt)

**Comment by dckiller51** [comment] 2023-10-01 00:38
@walberjunior 
Hello, I created a fork of hass_openwrt. I added the ability to play with services. I have an automation when HA restarts, it restarts the presence-detector service on my two APs.

**Comment by rmoesbergen** [comment] 2023-10-01 12:12
If you enable `fallback_sync_interval` (set it to > 0), and apply the one-liner patch below, it should be "fixed". It's more of a workaround than a fix. The problem is that offline detection is there, but if during the time that HA is offline there are no wifi device events, the presence detector does not detect that HA was offline and will not do a full sync. With the patch below, a periodic full sync will happen every `fallback_sync_interval` seconds, like the 1.X version used to do. Let me know if this helps.

```
diff --git a/presence-detector.py b/presence-detector.py
index d0f455f..1d9cd60 100755
--- a/presence-detector.py
+++ b/presence-detector.py
@@ -227,7 +227,7 @@ class PresenceDetector(Thread):
                 item: QueueItem = self._queue.get(timeout=queue_timeout)
             except queue.Empty:
                 # Perform a periodic full sync
-                self._do_full_sync(away_only=True)
+                self._do_full_sync()
                 continue
 
             if item.action == QueueItem.Action.QUIT:
```

**Comment by walberjunior** [comment] 2023-10-03 02:07
> self._do_full_sync()

Done. I will test and get back to you.

Thanks

**Comment by rmoesbergen** [comment] 2023-10-20 14:35
This is in v2.1.0. Closing this now, please re-open if there's still an issue.

**Closed by rmoesbergen** 2023-10-20 14:35 UTC
